[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log

[program:fastapi]
command=uvicorn src.api:app --host 0.0.0.0 --port 8000
directory=/app
autostart=true
autorestart=true
stdout_logfile=/var/log/fastapi.log
stderr_logfile=/var/log/fastapi_err.log

[program:streamlit]
command=streamlit run app.py --server.port=8501 --server.address=0.0.0.0
directory=/app
autostart=true
autorestart=true
stdout_logfile=/var/log/streamlit.log
stderr_logfile=/var/log/streamlit_err.log
